


project:   
  title: ScrivQ  
  preview:   
    port: 5556  
book:   
  title: Hello, ScrivQ  
  abstract: The ScrivQ Template  
  description: 🚀 Template Scrivener project designed for Quarto and Pandoc that exports multiple files, handles cross-references, manages bibliography, and builds complex YAML (it features hundreds of built-in parameters ready to be included/excluded from compile with many useful links to the documentation). Outputs Books in PDF, HTML, DOCX and Websites in HTML.  
  site-path: _site/  
  reader-mode: true  
  navbar:   
  page-navigation: true  
  back-to-top-navigation: true  
filters:   
  - citetools  
format:   
  html:   
    metadata:   
      author-meta: Bernardo César Diniz Athayde Vasconcelos  
      date-meta: 2023-08  
      subject: workflow  
      keywords: [Sophrosyne, Platão, Aristóteles]  
    theme:   
      light: [Pulse]  
      dark: [Cyborg]  
    include-before: |  
      <style>
      @import url('https://fonts.googleapis.com/css2?family=Alegreya+Sans:ital,wght@0,400;0,700;1,400;1,700&family=Alegreya:ital,wght@0,400;0,700;1,400;1,700&display=swap');
      @import url('https://fonts.googleapis.com/css2?family=Source+Code+Pro:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,200;1,300;1,400;1,500;1,600;1,700;1,800&family=Source+Sans+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700;1,900&family=Source+Serif+Pro:ital,wght@0,200;0,300;0,400;0,600;0,700;0,900;1,200;1,300;1,400;1,600;1,700;1,900&display=swap');
      .callout-header {
      background-color: transparent!important;
      }
      </style>
  
    toc: true  
    number-sections: true  
    number-depth: 3  
    linestretch: 1.5  
    fontsize: 12pt  
    fontfamily: Alegreya  
    mainfont: Alegreya  
    sansfont: Alegreya Sans  
    monofont: Source Code Pro  
    code-link: true  
    code-copy: true  
    code-tools: true  
    code-fold: show  
    code-line-numbers: true  
    code-overflow: wrap  
    appendix-style: default  
  pdf:   
    pdf-engine: lualatex  
    papersize: a4  
    documentclass: scrbook  
    classoption:   
      - oneside  
      - numbers=noenddot  
      - titlepage  
      - toclink=all  
      - toc=bibliography  
    geometry:   
      - top=2cm  
      - bottom=2cm  
      - head=1cm  
      - foot=1cm  
      - left=2cm  
      - marginparwidth=4cm  
      - textwidth=12cm  
      - marginparsep=1cm  
    cap-location: bottom  
    pagestyle: headings  
    hyperrefoptions:   
      - pdfstartview=FitR  
      - pdfpagemode=UseOutlines  
      - breaklinks=true  
      - pageanchor=true  
      - linktoc=all  
      - hyperfootnotes=false  
      - bookmarksnumbered  
    header-includes: |  
      \usepackage{setspace}  
      \usepackage{etoolbox}  
      \usepackage{metalogo}  
      \setsansfont{AlegreyaSans-Regular}[Extension = .otf , BoldFont = AlegreyaSans-Bold , ItalicFont = AlegreyaSans-Italic , BoldItalicFont = AlegreyaSans-BoldItalic ]  
    standalone: true  
    latex-auto-install: true  
    latex-auto-mk: true  
    latex-tinytex: true  
    keep-tex: true  
    babel-lang: brazilian  
    babel-otherlangs:   
      - english  
      - ancientgreek  
      - sanskrit  
    toc: true  
    toc-depth: 3  
    lof: true  
    lot: true  
    number-sections: true  
    number-depth: 3  
    top-level-division: chapter  
    linestretch: 1.3  
    fontsize: 12pt  
    fontfamily: Alegreya  
    mainfont: Alegreya  
    mainfontoptions:   
      - Numbers=Proportional  
      - Numbers=Lowercase  
    sansfont: Alegreya Sans  
    citecolor: RoyalBlue  
    linkcolor: RoyalBlue  
    toccolor: black  
    code-line-numbers: true  
    code-overflow: wrap  
    appendix-style: default  
    float: true  
    csquotes: true  
execute:   
  output: asis  
  cache: true  
  freeze: auto  
citation: true  
link-fields: false  
link-citations: true  
link-bibliography: true  
notes-after-punctuation: true  
citeproc: false  
verbose: false  
verbosity: ERROR  
validate-yaml: false
